name: Build Nuxt
on: [push, pull_request]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Nuxt
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: nuxt install
        run: yarn install
      - name: Nuxt to Github Pages
        run: |
              cd ./portfolio
              yarn generate
              cd ./dist
              git init
              git add -A
              git commit -m 'github action commit'
              git push -f https://harukei-tech:${{ secrets.GITHUB_TOKEN }}@github.com/harukei-tech/portfolio_web2.git master:gh-pages
        shell: bash
